name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
